version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync build/ s3://navdeepfinalyearproject
      - aws cloudfront create-invalidation --distribution-id E37EL0E68ND4IE --paths "/*"
artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
